### ISSUE TITLE
how to get annotation.csv of hg38?

### ISSUE THREAD

**Issue by Gray-Tu** [compbiolabucf/AS-Quant#1]
Hi. thank you for this cool tool, but I can't finish analysis because I got a error.

```
Traceback (most recent call last):
  File "as_quant.py", line 86, in <module>
    ann_file_reader= open(species_folder+'annotation.csv', "rt")
FileNotFoundError: [Errno 2] No such file or directory: 'hg38/annotation.csv'
```
my cmd is like
```
python3 as_quant.py -s hg38 -i group01/ group2/ -o output
```

It seem need a `hg38` folder, but I don't find it.

Best,
Gray

**Comment by naimafahmi** [comment]
Thank you for trying our tool. Can you please pull again and try? hg38 folder should be here.

**Comment by Gray-Tu** [comment]
I found it. Thank you.
