### ISSUE TITLE
How to use AS-Quant for species other than human and mouse?

### ISSUE THREAD

**Issue by yifangt** [compbiolabucf/AS-Quant#3]
While I am trying to use as-quant to species other than human/mouse,
1) What type of annotation file should be provided, if needed?
2) How to designate the conditions if there are more than two groups and multiple samples (e.g. replicates)?
I am aware the as-quant.py script will need be modified. Thanks a lot!

**Comment by naimafahmi** [comment]
Hello yifangt,

1. The annotation files for hg19, hg38 and mm10 are provided with the code. You need to use them, they are formatted accordingly.
2. AS-Quant works with only two groups, but each group can have multiple replicates/samples. You need to provide the parent directory of  each group and put only the bamfiles inside them. 
Example: "/main_dir/Group1" will contain < rep1_1.bam, rep2_1.bam, rep3_1.bam.....> and "main_dir/Group2" will contain < rep1_2.bam, rep2_2.bam, rep3_2.bam.....>. Hope it helps.

**Comment by yifangt** [comment]
Thanks for clarifying the conditions of more than 2 groups.
Back to my first question, I saw in the code the annotation file `annotation.csv` seems not common GTF or GFF file. My species is plant, NOT human or mouse. How should I create the annotation file for my plant genome?

In another way, how were your annotation files for hg19/hg38 and mm10 generated that I can adapted to create my own annotation file(s) for species like arabidopsis/rice/wheat, etc?

Thanks again!

**Comment by naimafahmi** [comment]
AS-Quant cannot be used for other species. You can prepare the annotation.csv file by yourself using UCSC annotation, but you will also need the list of splicing events for other species, which is not included in the current version of AS-Quant.

**Comment by yifangt** [comment]
Thanks!
Any reference to prepare `"the list of splicing events for other species"`, if handy? 
That's the missing piece of the puzzle I am trying to find out to make use AS-Quant for my species.

**Comment by naimafahmi** [comment]
There were a lot of analysis and pre-processing of the data. That is why we didn't provide that part in our code and kept it pre-annotated. You can find more about this in our manuscript [https://www.mdpi.com/1422-0067/22/9/4468](url)

**Comment by yifangt** [comment]
Thanks a lot!
