### ISSUE TITLE
make_plot.py errors

### ISSUE THREAD

**Issue by danphillips28** [compbiolabucf/AS-Quant#4]
Hi! Thanks for making this nice package. I'm really hoping I can get it to work, particularly the visualisation script. 

I have been trying to get make_plot.py to work but have been met with the following errors. First on my own data;

`python3 make_plots.py -s human -i /bam.files/Day0.KD.bams/ /bam.files/Day0.sc.bams/ -o .`
Traceback (most recent call last):
  File "make_plots.py", line 251, in <module>
    Process_user_inputs(region, input1_dir, input2_dir, s1_namelist, s2_namelist, g1_name, g2_name, output_dir, ann_list)
  File "make_plots.py", line 145, in Process_user_inputs
    exList = GeneDict[geneID]
KeyError: 'ACOX1'

And then on the sample mouse data;

`python3 make_plots.py -s mouse -i ./sample_input_mouse/group1/ ./sample_input_mouse/group2/ -o .`
Number of isoforms found for gene ACOX1: 4
Generating read coverage plots...
Traceback (most recent call last):
  File "make_plots.py", line 251, in <module>
    Process_user_inputs(region, input1_dir, input2_dir, s1_namelist, s2_namelist, g1_name, g2_name, output_dir, ann_list)
  File "make_plots.py", line 172, in Process_user_inputs
    for i, ax1 in enumerate(axes[0:len(s1_namelist)]):
TypeError: 'AxesSubplot' object is not subscriptable

Do you have any idea what is going wrong? I presume it is to do with package installations, as I am using a HPC and generally find version control very confusing. Also, I get the impression from the documentation that I specify the coordinates _after_ submitting this line, is that correct? I'd really like to get this visualisation method to work, so greatly appreciate your help. 

Thanks,
Dan

**Comment by naimafahmi** [comment]
Hello, 
Can you try try the code again and let me know if you find any issues anymore? We have released a new version.
