### ISSUE TITLE
as_quant.py

### ISSUE THREAD

**Issue by astulaaa** [compbiolabucf/AS-Quant#5]
Hello,

I am trying to work with bam file which is a subset from chr17.
I encountered this error.  
"[main_samview] fail to get the reference name. Continue anyway."
First I thought it might be 'chr' being denoted in as-quant reference files but not in bam file. But after removing 'chr' from reference files, I got the same error. What could be the reason?

Update. Solved. If bam file does not have 'chr' notation, it is neccessary to remove 'chr' not only from the reference files (A3SS.csv, annotation.csv, RI.csv, etc) but also from script as_quant.py lines 18 and 19. Hope that helps !

Regards,
Asta

**Comment by ChaeminLim75** [comment]
I was struggling with the same issue.
Thank you for giving the useful information!

**Comment by BirongZhang** [comment]
> Hello,
> 
> I am trying to work with bam file which is a subset from chr17. I encountered this error. "[main_samview] fail to get the reference name. Continue anyway." First I thought it might be 'chr' being denoted in as-quant reference files but not in bam file. But after removing 'chr' from reference files, I got the same error. What could be the reason?
> 
> Update. Solved. If bam file does not have 'chr' notation, it is neccessary to remove 'chr' not only from the reference files (A3SS.csv, annotation.csv, RI.csv, etc) but also from script as_quant.py lines 18 and 19. Hope that helps !
> 
> Regards, Asta

Hi Asta，

I am looking at this tool.

Before I start using it , may I ask **which method you used to get BAM file**? I use STAR a lot, so if STAR works, I can use the data I already have. Also, if **STAR** is available, _are there any special parameters to be aware of_?

Any advices would be highly appreciated! Thanks!

Kind regards,
Birong

**Comment by astulaaa** [comment]
My apologies for taking long to respond. 
**I used BAM files made using STAR**. The parameters used are as follows: 
_SortedByCoordinate, --chimOutType WithinBAM --chimSegmentMin 15 chimMainSegmentMultNmax 1, quantMode                         TranscriptomeSAM; twopassMode  Basic_ 
Nothing very special in terms of parameters to my understanding? Is there any parameter I should pay special attention to?

Thank you for your follow up!
Asta

**Comment by naimafahmi** [comment]
The splicing events and the genome annotation in AS-Quant, both use chromosome name in this format: 'chr1' , not '1'. If your bamfiles have chromosome name like that, please change it to 'chr1', 'chr2', 'chr3', ...
